.language: node_js
node_js:
  - '11'
env:
  JSONPLACEHOLDER_URL: https://jsonplaceholder.typicode.com
  JSONPLACEHOLDER_TIMEOUT: 5000
  NODE_ENV: development
  TYPEORM_CONNECTION: mysql
  TYPEORM_USERNAME: root
  TYPEORM_PASSWORD:
  TYPEORM_HOST: localhost 
  TYPEORM_PORT: 3306
  TYPEORM_DATABASE: nestjs_seed
  TYPEORM_MIGRATIONS: migration\*.ts
  TYPEORM_MIGRATIONS_DIR: migration
  APM_SERVICE_NAME: 
  APM_SERVICE_URL:
script:
  - npm i
  - echo -e "" >> .env
  - npm run test:cov
