apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: "$CI_PROJECT_NAME-admin"
  namespace: "$PROJECT_NAMESPACE-$CI_COMMIT_REF_NAME"
spec:
  roleRef:
    kind: ServiceRole
    name: "$CI_PROJECT_NAME-admin"
  subjects:
  - properties:
      request.auth.claims[roles]: "$CI_PROJECT_NAME-admin"
