name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        echo -e "NODE_ENV=development\nJSONPLACEHOLDER_URL=https://jsonplaceholder.typicode.com\nJSONPLACEHOLDER_TIMEOUT=5000\nTYPEORM_CONNECTION=mysql\nTYPEORM_USERNAME=root\nTYPEORM_PASSWORD=\nTYPEORM_HOST=localhost\nTYPEORM_PORT=3306\nTYPEORM_DATABASE=nestjs_seed\nTYPEORM_MIGRATIONS='migration\*.ts'\nTYPEORM_MIGRATIONS_DIR=migration\nAPM_SERVICE_NAME=\nAPM_SERVICE_URL=" >> .env
        npm run build --if-present
        npm run test:cov

      env:
        CI: true